#!/bin/bash

echo "🚀 Domus Global Deployment Guide"
echo "================================="
echo ""
echo "Choose your deployment platform:"
echo ""
echo "1. 🚄 Railway (Recommended - Easiest)"
echo "   → Go to: https://railway.app"
echo "   → Connect GitHub account"
echo "   → Click 'New Project' → 'Deploy from GitHub repo'"
echo "   → Select: JamesDavis95/domus-conveyancing"
echo "   → Railway will auto-detect and deploy!"
echo ""
echo "2. 🟣 Render (Also very easy)"
echo "   → Go to: https://render.com"
echo "   → Connect GitHub"
echo "   → New Web Service → Connect repository"
echo "   → Build: pip install -r requirements.txt"
echo "   → Start: python -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "3. ⚫ Vercel (Frontend-focused but works)"
echo "   → Go to: https://vercel.com"
echo "   → Import Git Repository"
echo "   → Select your repo and deploy"
echo ""
echo "4. 🪰 Fly.io (Manual CLI required)"
echo "   → Need to complete authentication first"
echo ""
echo "📝 All platforms will give you a live URL like:"
echo "   → Railway: https://domus-global-production.up.railway.app"
echo "   → Render: https://domus-global.onrender.com"
echo "   → Vercel: https://domus-global.vercel.app"
echo ""
echo "✅ Your code is ready to deploy!"