services:
  web:
    build: .
    command: ['python','-m','uvicorn','app_clean:app','--host','0.0.0.0','--port','8000']
    ports: 
      - "8000:8000"
    environment:
      - ENV=production
      - PORT=8000

  caddy:
    image: caddy:2
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - web
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped