version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:16
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: domus
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio:/data

  clamav:
    image: clamav/clamav:1.3
    ports: ["3310:3310"]

  api:
    build: .
    command: uvicorn app_secured:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:domus@postgres:5432/postgres
      AUTH_ENABLED: "false"
      S3_BUCKET: domus
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_REGION: us-east-1
      S3_SECURE: "false"
      CLAMAV_ENABLED: "true"
      CLAMAV_HOST: clamav
      CLAMAV_PORT: "3310"
      DATA_DIR: /data/uploads
    ports: ["8000:8000"]
    depends_on: [postgres, minio, clamav]
    volumes:
      - ./:/app
      - uploads:/data/uploads

volumes:
  pgdata:
  minio:
  uploads:
