app = "domus-planning-platform"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile.fly"

[env]
PORT = "8000"
[[services]]

source = "data"
destination = "/data"

internal_port = 8000
protocol = "tcp"
processes = ["app"]
  [services.concurrency]
  type = "connections"
  soft_limit = 20
  hard_limit = 25
  [[services.ports]]
  port = 80
  handlers = ["http"]
  [[services.ports]]
  port = 443
  handlers = ["tls","http"]
  [[services.http_checks]]
  path = "/health"
  interval = "15s"
  timeout = "2s"
  method = "get"
  protocol = "http"
  tls_skip_verify = false
  restart_limit = 0

[[mounts]]
  source = "data"
  destination = "/data"
