[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
ENVIRONMENT = "production"
PYTHONPATH = "/app"

[[services]]
name = "web"
source = "."