services:
  - type: web
    name: domus-planning-platform
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: domus-planning-db
          property: connectionString
      - key: FORCE_DEPLOY
        value: "2025-10-01-production"
  
  - type: pserv
    name: domus-planning-db
    env: postgresql
    plan: starter
    region: oregon
    databaseName: domus_planning
    databaseUser: domus_user