services:
  - type: web
    name: domus-planning-platform
    env: python
    plan: starter
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: python app_minimal.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PORT
        value: 10000